---
title: "Virginia Election Project"
author: "Taylor Atkins"
execute:
  echo: true
format:
  html:
    self-contained: true
    code-tools: true
---


```{r setup, include=FALSE, warning=FALSE, message=FALSE}


library(tidyverse)
library(janitor)
library(kableExtra)
library(here)
options(scipen = 999)
options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tigris)
library(sf)
library(tidycensus)
library(htmltools)
library(janitor)
library(here)
library(mapview)
library(leafsync)
library(leaflet.extras2)
options(tigris_class = "sf")


#load saved joined data file from previous script
joined_vacomparison <- readRDS(here("processed_data", "joined_vacomparison.rds"))



```


# Comparing Virgnia Gov vs. Prez



```{r}

joined_vacomparison <- joined_vacomparison %>% 
  mutate(
    dem_dif = round_half_up((pct_mcauliffe - biden_pct), 2),
    rep_dif = round_half_up((pct_youngkin - trump_pct), 2)
  ) 

```

```{r}

#joined_vacomparison <- joined_vacomparison %>% 
  #arrange(dem_dif)

```

```{r}

joined_vacomparison <- joined_vacomparison %>% 
  relocate(dem_dif, rep_dif, .after = locality)
head(joined_vacomparison)
tail(joined_vacomparison)

```




```{r}

# uncomment to run, then recomment it out so you don't run it every time

#census_api_key("2a6f8c21a30d3024e038d67d7d4eba647dc79cd4", install=TRUE)


```

```{r}
#chose variables we want
myvars <- c(totalpop = "B01003_001",
            medincome = "B19013_001",
            medage = "B01002_001"
)
```


```{r}
#pull for VA counties
va_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       state = "VA",
                       output = "wide",
                       geometry = TRUE)

va_counties_withgeo
```

```{r}
#all counties in the US
all_counties_withgeo <- get_acs(geography = "county",
                       variables = c(myvars),
                       output = "wide",
                       geometry = TRUE)

all_counties_withgeo
```

```{r}
#remove MOE columns - they all end with "M"
va_counties_withgeo <- va_counties_withgeo %>%
  select(-ends_with("M"))

va_counties_withgeo
```

```{r}
#remove that trailing "E"
colnames(va_counties_withgeo) <- sub("E$", "", colnames(va_counties_withgeo)) # $ means end of string only

va_counties_withgeo
```

```{r}

va_counties_withgeo <- va_counties_withgeo %>% 
  mutate(NAM = str_to_upper(NAM))

```

```{r}

va_counties_withgeo <- va_counties_withgeo %>%
  rename("locality" = "NAM")

```

```{r}

joined_vacomparison <- joined_vacomparison %>% 
  mutate(locality = paste(locality, ", VIRGINIA", sep = ""))

```

```{r}

va_counties_data <- full_join(va_counties_withgeo, joined_vacomparison)

```
Mapping Virginia counties with mapview

```{r}

mapview(va_counties_data, zcol = "dem_dif")



```


To turn off legends, hover text, popups


```{r}

mapview(va_counties_data, zcol = "dem_dif", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1,
         legend = FALSE, 
         label = FALSE, 
         popup = FALSE)


```

Customize labels
```{r}

mylabel <- glue::glue("{va_counties_data$locality} {va_counties_data$dem_dif}")


mapview(va_counties_data, zcol = "dem_dif", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1,
         label = mylabel)

```

Customize popups
```{r}
mypopup <- glue::glue("<strong>{va_counties_data$locality}</strong><br />
                      Total Population: {va_counties_data$totalpop}<br />
                      Difference in D Elections: {va_counties_data$dem_dif}<br />
                      Median Income: ${va_counties_data$medincome}<br />
                      Median Age: {va_counties_data$medage}") %>% 
  lapply(htmltools::HTML)

# mylabel <- glue::glue("{all_data$State} {all_data$PctChange10_20}%") %>%
#   lapply(htmltools::HTML)

```


```{r}

head(mypopup)

```


```{r}

mapview(va_counties_data, zcol = "dem_dif", 
         col.regions = RColorBrewer::brewer.pal(9, "Blues"), 
         alpha.regions = 1,
         popup = mypopup,
         label = mylabel)

```
