project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Taylor Atkins" 
    right: 
      - icon: github
        href: https://github.com/eatkins1
  title: "Taylor's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      


format:
  html:
    theme: quartz
    css: styles.css
    toc: true



