---
title: "Example of personal writing from class"
author: "Taylor Atkins"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true
---

This is a piece.

> **In Times of Need**
>
> How the first Decade of the AIDS Epidemic Changed GW Student Life
>
>             On June 5, 1981, the United States Center for Disease Control (CDC) published an article describing five cases of a rare lung infection, Pneumocystis Carinii Pneumonia (PCP). This rare disease was found in five gay men in the Los Angeles area who were all previously healthy adults. In the reports of these cases, the patients present other unusual infections indicating an immune system that\'s not working. By the time of this report, two of the patients are already dead. On the same day, a dermatologist in New York reports to the CDC a cluster of cases of an unusually rare and aggressive form of cancer, Kaposi\'s Sarcoma (KS), among gay men. Kaposi\'s Sarcoma, like PCP, indicates a weakened immune system to doctors. 
>
>             Within days the CDC establishes a Task Force on Kaposi\'s Sarcoma and Opportunistic Infections to identify risk factors and build a stronger understanding of the unnamed syndrome. Quickly news spreads of \"gay men\'s pneumonia\" or a \"gay cancer,\" partly due to a New York Times article published July 3rd. By the end of August of that year, 108 patients had been reported. Of those patients, 107 of them were male, 94% of the ones with a known sexuality were gay or bisexual, and 40% of those patients were already dead. By December, the first five infant patients are seen showing symptoms of severe immune deficiency, including PCP. At least three of these infants are known to be the children of drug users and sex workers. Also, in December, the \"KS poster boy,\" Bobbi Campbell, came forward as the first patient to be public about their KS diagnosis. He publishes a newspaper column on his experiences with \"gay cancer\" in the *San Francisco Sentinel*. By the year's end, nearly 50% of the 337 reported cases had died in the United States.
>
>             In April of 1982, the first congressional hearings were held in response to this possible public health crisis. During this, Dr. James Curran estimates that tens of thousands of individuals could have been infected already. During the early half of the year, a few community-driven organizations are formed for the sake of providing information to gay men in an attempt to stop spreading if possible. In the May 11 New York Times article, the term GRID (Gay-Related Immune Deficiency) is used for the first time and would go on to widely popularize misinformation that this illness could only affect gay men. In June 1982, the first studies were published that suggested a link between sexually transmitted diseases and this burgeoning epidemic which led to a big push from gay communities on safer sex habits. By July, the first patients with hemophilia with no other known risk factors appear to have the same syndrome; by the time this is reported, two of the three patients are dead. On September 24, 1982, for the first time, the CDC used the term Acquired Immune Deficiency Syndrome, AIDS.[\[1\]](#_ftn1)
>
>             The epidemic would spread from there until it reached the point of a national issue. Scientists determined that a newly detected virus caused it three years after being named. That year AIDS reached a new high in national attention for two notable reasons. One of these was a legal battle regarding a teenager who was refused entry to his middle school because he had contracted AIDS from blood transfusions related to his hemophilia. The other thing that brought national attention to AIDS was President Ronald Reagan mentioning AIDS for the first time in September of 1985 in an attempt to quell the complaints that federal funding for AIDS research was inadequate. 1985 is important for this paper because it is the first time AIDS has been mentioned in The George Washington University archives. This first mention from a source that isn\'t a student publication is the George Washington University News Release. This news release offers a bleak perspective on AIDS as a disease that they can\'t do anything to treat, like dementia or most forms of cancer.[\[2\]](#_ftn2) This was followed up by about 16 GW Hatchet articles covering and mentioning AIDS that year alone which expressed fear of the disease, disdain for protestors against federal funding, discussion of the treatment of those with AIDS, and much more. 
>
>             This paper investigates how the first decade of the AIDS epidemic shaped GW students\' lives and the campus environment. Through an analysis of the LGBTQ+ organizations on campus and in D.C., the fear and hatred generated and response to such, the AIDS-related medical studies on campus, and the NAMES Project AIDS Memorial Quilt that came to GW in 1992. ***I will argue that GW changed positively during and after the AIDS epidemic.***
>
> **Organizations Around Campus**
>
>             One of the most important aspects of student life on campus is the student organizations on campus, and the organizations that GW students interact with. The goals of these organizations and their membership go a long way to indicate the standing of groups on campus. *During the first decade of the AIDS epidemic, there was a noticeable amount of positive growth in the LGBT community on campus. Organizations grew and became more relevant and well-known, and they also started to shift to focus more on activism work.*
>
> To investigate the LGBT organizations on and around campus and how they changed, we must begin with the social standings of these organizations before the AIDS epidemic. A significant trend seen in sources from before the epidemic is a sense that the GW LGBT organization, which has gone by many names, is one of the strongest and longest-standing of any of the schools in the D.C. area. The Gay People\'s Alliance (GPA) of GW was so well established in its home school that it was known for supporting LGBT organizations on other campuses, like Gallaudet University\'s Lambda organization.[\[3\]](#_ftn3) Right at the very precipice of the epidemic, the GPA was seeing the membership boom due to the shifting political attitudes of the time.[\[4\]](#_ftn4)
>
>             Organizations on campus held a large number of events that were focused on the AIDS epidemic. There are several events held for Gay Awareness Week[\[5\]](#_ftn5) held by the LGBA or an Issue Awareness Night discussion on HIV/AIDS held by the Student Association.[\[6\]](#_ftn6) A significant shift that occurred during the AIDS epidemic was LGBT organizations shifting from strictly social into the political sphere. This change was partly of their own accord but was also a result of a wave of homophobia and anti-gay legislation likely fueled by the AIDS epidemic.[\[7\]](#_ftn7) This would go so far as to cancel pre-established events to push more educational and outreach programs.[\[8\]](#_ftn8) For example, the LGPA participated in the First National March on Washington for Gay and Lesbian Rights.[\[9\]](#_ftn9) On top of organizations on campus working to improve the environment, there were outside organizations involved in the campus life of LGBT students.
>
>             The organization Kaiser Permanente proposed performing a show, *Secrets*, which is a story about AIDS and would be put on to raise awareness and give accurate information on the epidemic. This event was co-sponsored by the AIDS Education Committee and the LGPA.[\[10\]](#_ftn10) When discussing this topic, one organization, in particular, appears numerous times, Whitman-Walker Clinic. Whitman-Walker is an LGBT-specific clinic that was founded shortly before the epidemic and would go on to be a first responder and leader in education, prevention, and treatment for HIV/AIDS. On several occasions, the GPA/LGPA/LGBA would raise money for Whitman-Walker. This included special events for this goal, and their donations were explicitly for Whitman-Walker\'s AIDS programs.[\[11\]](#_ftn11) Likewise, the LGBT community on campus actively promoted the clinic and handed out their AIDS Education Fund pamphlets that provided a lot of important information in a short and easily understandable format.[\[12\]](#_ftn12) This was an essential push for LGBT students and organizations on campus to support and be supported by off-campus organizations, which would further enrich the GW environment and provide aid to many more beyond campus.
>
>             When looking at the organizations on campus\' impact on the environment for LGBT people, it seems to indicate a positive shift. Not only were the pre-existing organizations empowered, but they also pushed toward the political sphere. This shift was likely partially incited by the AIDS epidemic and made the campus environment better. Off-campus organizations like Kaiser Permanente and Whitman-Walker Clinic also supported students. Using their new political lean, the students on campus would also support these organizations, which ultimately had significant positive ramifications for the GW campus and D.C. as a whole.
>
> **Loss and Hate**
>
> Generally speaking, there was a positive change in the climate of GW during the AIDS epidemic, a major part of which was the work done by LGBT orgs. However, there were some examples from GW students of the treatment of gay people and people with AIDS that weren\'t nearly as positive. Some liken the treatment of people living with AIDS to that of lepers and how it is breeding a new wave of homophobia and discrimination.[\[13\]](#_ftn13) This time period was also shaped by a rise in homophobic sentiment sparked by the AIDS epidemic. The epidemic significantly raised fears about and being around LGBT students. This can be highlighted by a particular event which involved an employee at GW who had AIDS and the way the school handled it spurred a larger response than would have otherwise. Finally the blatant homophobic hatred was on the rise in this time, in part, due to the epidemic and increase in social awareness mostly due to the epidemic. *During the AIDS epidemic, a lot was distinctly negative for GW students, particularly the fear and hatred generated.*
>
> The AIDS epidemic incited a new awareness of LGBT people in society, and with that brought a new wave of fear over the disease that many associated with them. At the time, the fear over AIDS was best characterized as a fear of gay people. AIDS was so prolific that it was wholly expected that at least one student, teacher, or faculty member at any given university would contract it. Many students in particular were worried about staying in dorms where they could be in close proximity to students with AIDS.[\[14\]](#_ftn14) This fear could be extrapolated to America at large. Especially early on in the epidemic many people were scared and confused about how AIDS worked and was spread. Some were asking if it could be spread from a bus seat or from documents handled by a gay co-worker. Despite health officials reassuring otherwise, many hospital patients in Los Angeles were stockpiling their own blood in case of surgery to avoid AIDS-contaminated blood.[\[15\]](#_ftn15) This was such a substantial and wide-spread fear that even in 2022 \"men who have sex with other men\" still can\'t donate blood until three months after their most recent sexual encounter, according to the American Red Cross.[\[16\]](#_ftn16) Although these fears are more general and not specific to GW, it can still be assumed that these fears, to some degree, were still present. This assumption can be made by the GW students who discussed this very subject. They likened this wave of fear to the Red Scare, an \'anti-communist\' witch hunt. \"Fear of AIDS has directed the wrath of society at its most innocent and vulnerable members,\" said one GW student in a Hatchet article.[\[17\]](#_ftn17)
>
> In 1990, The George Washington University Hospital came under fire for an AIDS-related incident. The incident was sparked when obstetrician-gynecologist, Benjamin Waxman, died from AIDS. The issue arose when GW Hospital leadership decided against informing former patients of Waxman of his condition. Leadership determined that the possibility of transmission from health-care provider to patient was so little that it was not worth informing patients and risking an overreaction, but this led to a larger reaction when patients eventually did find out. A patient of Waxman, Dale Stasi, didn\'t find out about the cause of his death until she asked another GWU faculty member. Stasi, who had just recently written a book on AIDS in the workplace, discussed how the leadership made of men didn\'t trust women to not be \'hysterical\' in regards to this reveal. Despite this, Waxman having AIDS was explicitly not kept a secret in his obituary, which was published locally in the Washington Times and the GW Hatchet. Waxman\'s ex-wife very intentionally didn\'t want this to be kept a secret, and, in part, wanted as many of Waxman\'s former patients to have this knowledge. On Waxman\'s part, according to his ex-wife, he took a step back from directly handling patients once he knew he was infected. Many posed in favor of informing patients and believed that what GW decided on was only going to brew more fear of contracting AIDS.[\[18\]](#_ftn18) This was a relatively rare instance of GW making a decision which could lead to direct harm for AIDS patients. This event blew up to the point of being on national news like The Washington Post. 
>
> In conjunction with the fear swirling around AIDS and its patients there was also a wave of anti-LGBT hate. One of the earliest instances of this rise in hate in the time period can be seen in a Gay People\'s Alliance meeting notes. This meeting heavily focused on homophobic hat that had been seen on campus and from GW students as well as prospects on what to do about it. The meeting started by talks about students\' hostile attitudes which included tearing down flyers for GPA events. As a response to this GPA members needed to discuss \"practical publicity alternatives\" to ensure that GWU students can get information on gay issues and events happening. This was followed by discussion on an unsuccessful attempt to meet with the Hatchet staff to protest a recent homophobic writing. The student members who were approached refused to discuss changing to a more unbiased stance on gay themes. The members of the GPA perceived a regression of GWU students\' attitudes towards gay and lesbian students.[\[19\]](#_ftn19) Relatively early in the AIDS epidemic LGBT students noted an increase in homophobic sentimentalities. 
>
> Just a few weeks before an article on the new wave of discrimination from AIDS was published, another article was published by a GW student who argued that \"sodomy and lesbianism can be called, at best, anatomically aberrant, not normal.\" This article compared someone\'s sexuality to one's race, which wasn\'t an uncommon response to homophobia in the sense of it being an immutable feature of someone. This article, however, took this in the opposite direction arguing how to \'change\' one\'s sexuality like trying to change someone\'s race.[\[20\]](#_ftn20) This article was published in the Hatchet and indicates the capability for students to hold this hate, and for the official student newspaper to publish it to the full campus. The final example that will be presented of the degradation of the GW campus for LGBT students during the AIDS epidemic is from 1990. The GW branch of the Young Americans for Freedom (YAF) published an article titled \"YAF\'s First Annual Enemies List.\" This list included the Lesbian and Gay People\'s Alliance (LGPA) with the explanation, \"You know why you\'re here.\" This was in response to an event held by LGPA, which offered to co-sponsor with YAF that featured a gay conservative speaker. During this, LGPA intended to discuss his gay activism instead of focusing on the ideas of conservatism.[\[21\]](#_ftn21) This response reflects how the anti-LGBT responses on campus grew general childish. The anti-LGBT work done on campus by students would diminish over time, likely, in responce to the strong boom in LGBT organizations and work done on campus. The event that occurred with Waxman was the primary major event that involved degradation of support for the LGBT community. In the end the pro-LGBT direction the social spaces on GW campuses led was, arguably, a stronger force than the hate and fear that was also generated at this time.
>
> **Medical Studies**
>
> Because of the nature of this subject, discussing a national epidemic, it only makes sense to include the environment of the medical studies and how it was reflected on the larger student body. The George Washington University School of Medicine & Health Sciences (SMHS) is one of the most exclusive medical schools, and the GWU Hospital is notable for its treatment of presidents and senators. Simply put, the medical field of GW is a highly respected and important part of the medical community, especially in D.C. With that knowledge, how GW\'s medical branches responded to the AIDS epidemic means more than just the students on campus but a role model for other medical schools and hospitals. *Early in the AIDS epidemic, The George Washington University went relatively above and beyond in its work on AIDS research which part of this would shape how students viewed the epidemic and LGBT people as a whole.*
>
>             Amid the AIDS epidemic, the medical center held a study on second-year medical students in conjunction with the NIMH AIDS Education Program. This study brought to light several key takeaways about non-LGBT students and, more notably, medical students who will likely have to care for AIDS patients at some point. Most medical students were ambivalent about caring for AIDS patients but were more concerned about having a choice in caring for them and the fear and stigma involved. These students were distrustful of guidelines regarding self-protection and were worried about the transmission of AIDS to themselves or family. The study determined that the social climate regarding care for AIDS patients may impact the students\' attitudes toward AIDS.[\[22\]](#_ftn22) The study showed how minimal compassion, at best, was granted to AIDS patients, and the study itself even suggests that a better social climate would improve the care given to patients. This highlights just how important the social environment can be in an epidemic.
>
> A year after this study, a program was proposed by the Department of Psychiatry and Behavioral Sciences titled the HIV/AIDS Consultation, Evaluation, and Treatment Service Program (HACETS). This program was intended to be psychiatric help for those with, likely to get, or family of those with HIV/AIDS. The services provided were stated to be for anxiety, depression, suicidality, interpersonal stresses, and family conflicts.[\[23\]](#_ftn23) This program was an essential service for many and indicated the state many people with AIDS were in because of the stated reasons for the service provided. 
>
> HACETS was so successful that the United States Department of Health and Human Services (DHHS) reached out to the AIDS Education Project at GW. The correspondence with the DHHS would request the adaptation of HACETS to be used as a training program for healthcare professionals.[\[24\]](#_ftn24) The program would first be sampled with the Whitman-Walker Clinic.[\[25\]](#_ftn25) This program would succeed in the greater D.C. area and further solidify the points from before on a larger scale. This was just one way in which The George Washington University was an important leader in the fight against AIDS in the D.C. area.
>
> **The NAMES Project AIDS Memorial Quilt**
>
>             *When discussing the period, it is helpful to look at a specific anchor point that truly highlights how much the environment on campus has changed for the positive despite this tragedy.* This event was selected because of its time period as well as its national significance. This event occurred just towards the end of the time period for this piece, so it can be best used to highlight how the environment on campus was at the ending. Along with this is how major of an event this was; being tied to a national event helps to make this point stand out in the timeline of events covered.
>
> Before delving into this segment, a bit more additional historical context is needed. Before the AIDS epidemic, LGBT people were rarely, if at all, considered and, as highlighted in a GW Hatchet article, were mainly perceived as a joke. Because of how little queer people were perceived in any serious manner, the legal struggles being battled were ignored. As mentioned in the same Hatchet article from August 10, 1972, homosexuality was illegal in 44 states, meaning jobs, including the US Government, could discriminate in hiring, or immigrants could be deported for being gay.[\[26\]](#_ftn26) Because of the state of the LGBT community before the AIDS epidemic, it took a lot of work to bring awareness to this issue facing, primarily gay people. A poll held from June to July of 1983 depicts a massive jump in who\'s aware of this epidemic, from 77% to 91%, but in comparison, the percentage of people who believed homosexuality should be considered an acceptable alternative lifestyle decreased slightly, from 34% to 32%.[\[27\]](#_ftn27) As seen from this data, people gained awareness of the AIDS epidemic, but overall, their compassion toward LGBT people had not improved. This was a big part of why AIDS Awareness Week would come about, to raise awareness of not just the disease but also the genuine people suffering from it, including gay people.
>
>             Arguably the most notable thing to raise awareness for AIDS and the suffering behind it was the NAMES Project AIDS Memorial Quilt, or the AIDS Quilt, which was a huge tapestry of quilt squares, each made to memorialize those who had died from AIDS. This piece was such a notable touchstone in the epidemic, partly because, as of 2020, it is the largest piece of community folk art in the world. Its prominent showing on the National Mall in Washington D.C. on October 11, 1987, was the Quilt\'s first display. After that, it traveled around the country on a tour that raised nearly \$500,000 for AIDS service organizations, as well as getting new panels added at every stop. By the end of the tour that year, the Quilt\'s size had tripled to over 6,000 panels. The Quilt would then be sent to eight countries on six continents for the first World AIDS Day, followed by another North American tour.[\[28\]](#_ftn28) 
>
> In 1992, the Quilt returned to D.C. and was displayed on the National Mall once more, this time nearly double the size it was at the end of 1987. 1992 is also when this touchstone circles back to The George Washington University. As a part of AIDS Awareness Week 1992, the Program Board arranged for a portion of the AIDS Quilt to come to campus. For the week of March 23^rd^, students, faculty, and outside community members could visit the GW ballroom to view several panels from the larger piece and pay their respects. It was estimated that roughly 2,000 students viewed the quilt during this time, meaning that a large portion of the student body favored paying respect to those who had died. As a part of the event, students could show their support through a special panel for GW students. Much of this event was held by student sponsors.[\[29\]](#_ftn29) This was a major show of support for those with and who had died from AIDS from the GW community. Admittedly, this strong support was almost exactly a decade after the AIDS epidemic began and five years after the Quilt started touring.
>
> The AIDS Quilt and its appearance on campus would have some lasting impact on the community. In 1997, as a part of Gay Awareness Week, the Lesbian Gay and Bisexual Alliance of GW held a workshop so that anyone who wanted to could add a panel.[\[30\]](#_ftn30) This indicates that the student body's desire to participate and show support had not faded after five years. This also indicates how the student body has had to become accustomed to the death of those around them, that this event to memorialize those who had died was a major event that groups were participating in. The continued support is another example of the on-campus LGBT organizations mobilizing during the AIDS epidemic. This is seen in how there wasn\'t any notable protesting held against the presence of the quilt which was an explicitly gay and political act, so this indicates how diminished the anti-LGBT front on campus was by this point. Along with this, the large scale of this event meant that GW as a university had to, at least, be aware of this and choose to allow it to be attached to the school. This shows how the school, even if in a passive way, was willing to support LGBT students.
>
> The AIDS Quilt depicts a major cultural reference point for the AIDS epidemic at GW, nationality, and globally. The quilt made to remember those who had died did a lot to raise awareness for how scary this disease was and those dying of it. An important point to take away is that it showed how much more prominent the conversation of gay people became on campus during the epidemic. It was also not the last time the Quilt was discussed on campus, and also wasn\'t the last major event held through GW about AIDS awareness. 
>
> **The Future and Conclusion**
>
>             *These changes seen from this first decade of the epidemic were not isolated and would bleed into the future of LGBT students on campus for years to come.* Most notably the shift towards activism and politics and the increase in membership of LGBT organizations have maintained in the decades since the beginning of the AIDS epidemic. The fact that these changes have been maintained over time just further emphasizes the impact on GW that the epidemic had. 
>
>             The population of students who are members of LGBT organizations has grown and stayed strong since the epidemic. One such way this can be seen is in the perseverance of a particular organization on campus, Delta Lambda Phi (DLP). DLP was a fraternity which catered to gay and bisexual men at GW and is the only queer men specific fraternity on campus. DLP was first seen, in the GW archives, in 1992 just towards the end of this paper\'s time period.[\[31\]](#_ftn31) After nearly 30 years, as of 2020, the organization is still around at GW.[\[32\]](#_ftn32) This highlights how the LGBT presence on campus has been maintained since the epidemic, but not only that it has grown. According to the GW Engage website, there are at least 8 officially recognized LGBTQ+ organizations on campus.[\[33\]](#_ftn33) This shows how the students have spread out from just being within a singular LGBT organization and developed more specialized groups for students. Of these groups there is a central umbrella LGBT organization, Allied in Pride, which is the largest. Allied in Pride boasts over 700 official members making it one of the largest organizations on campus, outnumbering GW College Republicans by a large margin.[\[34\]](#_ftn34)[\[35\]](#_ftn35) 
>
>             On top of growing in size GW\'s LGBT population has maintained its political lean over the years. Returning to DLP, the DC chapter was founded with the intent of being predominantly social, however it still was doing community work and fundraising for AIDS research.[\[36\]](#_ftn36) Despite the fact, at least in 1995, emphasized their social lean they still were doing inherently political work. This work being done under the guise of being strictly social shows just how deep this thread ran in LGBT groups. In the direct opposite of this is what Allied in Pride stated its mission to be. Allied in Pride intended to raise awareness of and advocate for LGBT people on campus through their social gatherings. The organization has done activism work for both GW and the greater DC area participating in politics on both levels in defense of LGBT people.[\[37\]](#_ftn37) This type of work was seen even earlier with the LGBA in 1997. During this year the LGBA sponsored Gay Awareness Week despite the fact that it was not a nationally recognized event. This was done to promote activism in young LGBTQ people and issues.[\[38\]](#_ftn38) This all shows how thoroughly entrenched in activism and political work LGBT students and organizations grew to become after the first decade of the AIDS epidemic, further highlighting the importance and positive trend of this moment in history.
>
> This particular subject is relatively unique in the academic fields. There is no significant scholarship on the subject of how the first decade of the AIDS epidemic shifted social spaces for LGBT people. Most research that was remotely similar was taking place after the scope of this piece and/or was well beyond college demographics. For instance, Rosser\'s piece in the journal AIDS Care from 2007 which researched the perceived decline in community engagement and visibility after the AIDS epidemic.[\[39\]](#_ftn39) This piece is particularly engaging because it may further support the thesis of this paper. This is because the perceived decline mentioned by Rosser was in relation to during the AIDS epidemic which showed a very high influx in activism. This was something that was partially reflected in the uptick in political activity from LGBT organizations on GW\'s campus. One of the few pieces that covers a similar topic to this paper is the book *The Social Impact of AIDS in the United States*. This book covers a wide range of the impacts caused by the epidemic, beyond the scope of this paper, but it does have a segment which is specifically dedicated to the first decade of the epidemic. This piece also particularly highlights the rise in activism in the LGBT community especially with AIDS Coalition to Unleash Power (ACT-UP).[\[40\]](#_ftn40) This book partially examined this time period but did no deep look into particularly university society. On top of this GWU has a very unique position as a university located in the heart of DC the student body then and now have had a strong political lean which makes the environment even more unique compared to even other universities.
>
> From many angles, the experience on GW\'s campus appeared to be making a positive trend regarding LGBT students during the AIDS epidemic. This is for several reasons. For one, the AIDS epidemic brought the LGBT community into prominence like never before and, as a result, brought them into the political sphere. This would extend to the GW campus for LGBT students. LGBT organizations at GW significantly grew in prominence during this time and began to shift towards political action orgs rather than solely social ones. This ties into the prominence and new wave of homophobia brought on by the epidemic. The anti-LGBT fear and hate generated was on the rise early in the epidemic, but, as a result of the shift in LGBT students and organizations on campus, was quashed and by the end of the decade was nearly non-existent. When analyzing the touchstone of the AIDS Quilt, it can likewise be seen how the society at GW was becoming more aware of the issues of AIDS and gay people. The AIDS Quilt would return to campus, and D.C. and GW students would also participate in this new tradition. The medical side of GW would make significant improvements. They investigated the beliefs and biases of medical students and how they could affect the care of AIDS patients, and they established the very successful HACETS program. Both of these emphasize that GW was a leader in AIDS research in the D.C. area at the time. All of these indicate and support the notion that the AIDS epidemic would lead to an overall positive change in the life of LGBT GW students.
>
> [\[1\]](#_ftnref1) \"A Timeline of HIV and AIDS,\" HIV.gov, accessed December 15, 2022, https://www.hiv.gov/hiv-basics/overview/history/hiv-and-aids-timeline#year-1982.
>
> [\[2\]](#_ftnref2) \"George Washington University News Releases.\" Washington, D.C.: George Washington University Libraries, 1985. The George Washington University.
>
> [\[3\]](#_ftnref3) Katherine Dugger, \"Area Campus Gay Groups Seek Official Recognition,\" *The Tower Catholic University Independent Newspaper*, November 16, 1984, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[4\]](#_ftnref4) Stephanie Heacox, \"Membership Increasing in GW Gay Society,\" *The GW Hatchet*, November 18, 1982, RG0122, Box #2, Folder 2, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[5\]](#_ftnref5) Lesbian, Gay, Bisexual Alliance, \"Gay Awareness Week 1997,\" April 14-19, 1997, RG0122, Box #1, Folder 6, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[6\]](#_ftnref6) College Republicans, College Democrats, Lesbian, Gay, Bisexual Alliance, et al., \"Issue Awareness Night, Topic: AIDS/HIV with Scott Fried,\" RG0122, Box #1, Folder 6, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[7\]](#_ftnref7) Julie Hansen, \"Gay Peoples\' Alliance: Dispelling Stereotypes,\" *The GW Hatchet*, November 18, 1982, p. 11-12, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[8\]](#_ftnref8) *Minutes of Gay People\'s Alliance Roundtable Discussion (12/3/85)*, July 9, 1986, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[9\]](#_ftnref9) Lesbian and Gay Peoples Aliance of GW, \"National March on Washington For Gay and Lesbian Rights,\" RG0122, Box #1, Folder 6, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[10\]](#_ftnref10) Kaiser Permanente, \"Secrets,\" *Program for Theater Program Presented by Kaiser Permanente*, February 1, 1991, RG0122, Box #2, Folder 3, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[11\]](#_ftnref11) Jim Graham, \"Letter from Whitman-Walker Clinic on Donation Made by Gay Peoples Alliance,\" *Whitman-Walker Clinic, Inc. letter*, May 30, 1986, RG0122, Box #2, Folder 3, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[12\]](#_ftnref12) Whitman-Walker Clinic, \"What Should I Do to Avoid AIDS?,\" *AIDS Education Fund*, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[13\]](#_ftnref13) Alan R. Cohen, Marshall Arbitman, \"AIDS: The New Enemy Within,\" *The GW Hatchet*, September 23, 1985, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[14\]](#_ftnref14) \"AIDS Scare Hits College Campuses,\" *The GW Hatchet*, November 4, 1985, p. 8, 14, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[15\]](#_ftnref15) Tom Morganthau et al., \"Gay America,\" *Newsweek*, August 8, 1983, pp. 30-40, RG0056 Series 1, Box #14, Folder 4, Multicultural Student Services Center records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[16\]](#_ftnref16) \"LGBTQ Donors,\" Blood Donation Eligibility for LGBTQ \| Red Cross Blood Services, accessed December 15, 2022, https://www.redcrossblood.org/donate-blood/how-to-donate/eligibility-requirements/lgbtq-donors.html.
>
> [\[17\]](#_ftnref17) Alan R. Cohen, Marshall Arbitman, \"AIDS: The New Enemy Within,\" *The GW Hatchet*, September 23, 1985, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[18\]](#_ftnref18) Malcolm Gladwell, \"AIDS Death and Ethics,\" The Washington Post (WP Company, April 16, 1991), https://www.washingtonpost.com/archive/local/1991/04/16/aids-death-and-ethics/72744866-1807-406f-9bbf-85c3f330d8c3/.
>
> [\[19\]](#_ftnref19) *Minutes of Gay People\'s Alliance Roundtable Discussion (12/3/85)*, July 9, 1986, RG0122, Box #1, Folder 8, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[20\]](#_ftnref20) G.P.A., Jordan Lorence, \"The Gay Rights Debate,\" *The GW Hatchet*, September 12, 1985, p. 5, RG0122, Box #2, Folder 2, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[21\]](#_ftnref21) David Mohan, \"YAF\'s Malicious Attack on Student Groups is the Last Straw,\" *The GW Hatchet*, October 25, 1990, p. 5, RG0122, Box #2, Folder 2, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[22\]](#_ftnref22) The George Washington University Medical Center, \"NIMH AIDS Education Project,\" November 1987, RG0059 Series 1, Box #1, Folder 16, Psychiatry and Behavioral Sciences Department records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[23\]](#_ftnref23) Dr. Jerry M. Weiner, \"Letter on the Announcement of the HIV/AIDS Consultation, Evaluation, and Treatment Service Program,\" *Department of Psychiatry and Behavioral Sciences at The George Washington University Medical Center*, June 23, 1988, RG0059 Series 1, Box #1, Folder 4, Psychiatry and Behavioral Sciences Department records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[24\]](#_ftnref24) Lewis L. Judd, \"Letter from DHHS to Dr. Jeffery S. Akman on Health Care Provider Training Program,\" *Department of Health & Human Services*, August 7, 1989, RG0059 Series 1, Box #1, Folder 11, Psychiatry and Behavioral Sciences Department records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[25\]](#_ftnref25) George A. Swales, \"Letter from DHHS to Dr. Jeffery S. Akman on the Results of Health Care Provider Training Program,\" *Department of Health & Human Services*, November 7, 1989, RG0059 Series 1, Box #1, Folder 11, Psychiatry and Behavioral Sciences Department records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[26\]](#_ftnref26) Vick. \"Like a Badge...\" *The GW Hatchet*, August 10, 1972, pp. 4.
>
> [\[27\]](#_ftnref27) Tom Morganthau et al., \"Gay America,\" *Newsweek*, August 8, 1983, pp. 30-40, RG0056 Series 1, Box #14, Folder 4, Multicultural Student Services Center records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[28\]](#_ftnref28) \"The History of the Quilt,\" History (The National AIDS Memorial), accessed December 15, 2022, https://www.aidsmemorial.org/quilt-history.
>
> [\[29\]](#_ftnref29) Mohab F Akhnoukh, ed., \"AIDS Awareness,\" in *The George Washington University Cherry Tree 1992*, vol. 85 (Washington, D.C., 1992), pp. 106-107, https://archive.org/details/gwu_cherry_tree_1992/page/n3/mode/2up?q=aids.
>
> [\[30\]](#_ftnref30) Lesbian, Gay, Bisexual Alliance, \"Paneling Workshop,\" *Gay Awareness Week NAMES Project AIDS Memorial Quilt*, RG0122, Box #2, Folder 5, GW Pride records, Special Collections Research Center, Gelman Library at The George Washington University.
>
> [\[31\]](#_ftnref31) \"Classified - Announcements,\" *The GW Hatchet*, March 5, 1992, 88 edition, sec. 44, p. 16, https://archive.org/details/gwu_hatchet_19920305/mode/2up?q=%22Delta+Lambda+Phi%22.
>
> [\[32\]](#_ftnref32) Lily Hatzenbeler, ed., \"Multicultural Greek Councils,\" in *The George Washington University Cherry Tree 2020*, vol. 112 (Washington, D.C., 2020), p. 118, https://archive.org/details/cherry_tree_2020/page/n121/mode/2up?q=%22Delta+Lambda+Phi%22.
>
> [\[33\]](#_ftnref33) GW engage, accessed December 15, 2022, https://gwu.campuslabs.com/engage/organizations?categories=14722.
>
> [\[34\]](#_ftnref34) GW engage, accessed December 15, 2022, https://gwu.campuslabs.com/engage/organization/allied-in-pride/roster.
>
> [\[35\]](#_ftnref35) GW engage, accessed December 15, 2022, https://gwu.campuslabs.com/engage/organization/gw-college-republicans/roster.
>
> [\[36\]](#_ftnref36) Jay Jagannathan, \"Delta Lambda Phi Offers 'Alternative' Fraternity,\" *The GW Hatchet*, October 2, 1995, 92 edition, sec. 16, p. 9, https://archive.org/details/gwu_hatchet_19951002/page/n7/mode/2up?q=%22Delta+Lambda+Phi%22.
>
> [\[37\]](#_ftnref37) Alexis L Clark, ed., \"Speak Your Voice Advocacy,\" in *The George Washington University Cherry Tree 2016*, vol. 108 (Washington, D.C., 2016), pp. 58-59, https://archive.org/details/gwu_cherry_tree_2016/page/n59/mode/2up?q=gay+activism.
>
> [\[38\]](#_ftnref38) Annie Nguyen, \"LGBA Celebrates 25 Years of GW Activism,\" *The GW Hatchet*, April 14, 1997, 93 edition, sec. 58, p. 7, https://archive.org/details/gwu_hatchet_19970414/mode/2up?q=gay+activism.
>
> [\[39\]](#_ftnref39) B. R. Simon Rosser, William West, and Richard Weinmeyer, \"Are Gay Communities Dying or Just in Transition? Results from an International Consultation Examining Possible Structural Change in Gay Communities,\" *AIDS Care* 20, no. 5 (May 16, 2008): pp. 588-595, https://doi.org/10.1080/09540120701867156.
>
> [\[40\]](#_ftnref40) National Research Council Staff et al., *The Social Impact of AIDS in the United States*, ed. Albert R Jonsen (Washington, D.C.: National Academy Press, 1993).
